### ISSUE TITLE
What's the application of this module?

### ISSUE THREAD

**Issue by patricknelson** [silverstripe/silverstripe-iframe#21]
Maybe the `README.md` or `userguide.md` files could provide more context about the usage of this module. Currently to me simply incorporating `<iframe>` tags (and maybe leveraging some auto-height capability) is exceedingly simple. How does this module simplify this task? e.g. I'm assuming maybe:
1. Does it provide functionality for inserting a centralized `<iframe>` tag (controlled as a standard `Page` subclass) into an `HtmlEditorField` instance? If so, that'd be cool and useful.
2. Does it just make it possible (on the flip side) to just provide content that can itself then be used as an iframe elsewhere without the extra template/cruft setup by the standard `Page.ss` template[s]?

Maybe this just needs more example code and, possibly more important, setup a simple example that demonstrates the context of the situation where you might need this instead of just implementing the `<iframe>` yourself in the CMS + template.

**Comment by robbieaverill** [comment]
PR at #36 to clarify the documentation a little
