### ISSUE TITLE
UX: Within CMS html as part of title is not being processed

### ISSUE THREAD

**Issue by raissanorth** [silverstripe/silverstripe-iframe#32]
The HTML tags that are part of the label description for the Iframe URL are not escaped and therefore displayed in the CMS:

![image](https://user-images.githubusercontent.com/14869519/38229297-53b13d72-375c-11e8-844d-d0e1e699cb56.png)

![image](https://user-images.githubusercontent.com/14869519/38229390-bd25d65a-375c-11e8-87d8-3f6620f27187.png)

**Comment by robbieaverill** [comment]
Fix at #33
