### ISSUE TITLE
Deprecate module in favour of an "IFrame block" for content blocks

### ISSUE THREAD

**Issue by robbieaverill** [silverstripe/silverstripe-iframe#38]
The UX for this module is a bit old and dated now. The fact that it has three TinyMCE instances on the page (aside from that sentence in itself) is unlikely to be compatible with modules such as externallinks, fulltextsearch etc that expect the content for a page to be in the "Content" field (note: it's also a known issue that this is also true for the elemental module right now).

I suggest we deprecate this module and replace it with a `silverstripe-elemental-iframeblock` module instead, then encouraging people to install and use that with silverstripe-elemental from then on. 

This module could still be used for the life of SilverStripe 4.x, but we'd drop support for it in SilverStripe 5.

cc @silverstripe/core-team @silverstripe/creative-commoners

**Comment by maxime-rainville** [comment]
Let the past die. Kill it if you have to. That's the only way to become what you were meant to be.

**Comment by chillu** [comment]
I'm OK with dropping commercial support, but can see the use case for it going forward (like Will mentions). I think for now, let's not worry about what's going to be maintained by who post 2022 (which is the support timelines for 4.x) unless there's going to be long and painful transition phase (like translatable to fluent). 

If you're worried about the user experience, we could remove it from the CWP default recipe, and make it an optional addition in CWP?

**Comment by robbieaverill** [comment]
I'm not particularly worried about it, just thought it might be a pattern we want to move away from going forwards so I thought I'd raise it for discussion. Maybe let's revisit closer to 2022 =)

**Comment by NightJar** [comment]
Should we close this (for now at least) then?

**Comment by robbieaverill** [comment]
Enough people want to keep it from the core team to say "no"
