### ISSUE TITLE
IFramePageController should extend PageController

### ISSUE THREAD

**Issue by robbieaverill** [silverstripe/silverstripe-iframe#39]
I think this was changed in 2.0.x with 5b8e0ba0b18a39267f3c9b8a050bb4eeeb0b8a6e, in the 1.0 line it extends PageController.

If we don't extend PageController then you don't get the standard templating etc so you'd lose some consistency in your site.

Switching the parent class may constitute an API change - how do we feel about changing it?

cc @robingram

**Comment by NightJar** [comment]
https://www.youtube.com/watch?v=FQRW0RM4V0k

**Comment by robbieaverill** [comment]
Fixed in #40 thanks @robingram
