### ISSUE TITLE
Frames must have title attribute

### ISSUE THREAD

**Issue by robbieaverill** [silverstripe/silverstripe-iframe#43]
**CWP 2.3.x-dev**

Issue description:
Ensures <iframe> and <frame> elements contain a non-empty title attribute

Impact: serious

Element location: `#Iframepage-iframe`

Element source:
`<iframe id="Iframepage-iframe" style="height: 500px; width: 100%; " src="https://demo.cwp.govt.nz/core/" class="iframepage-height-auto Iframepage-iframe"><p><span>Sorry you have iFrames disabled.</span></p></iframe>`

To solve this violation, you need to fix at least one (1) of these issues:
* aria-label attribute does not exist or is empty
* aria-labelledby attribute does not exist, references elements that do not exist or references elements that are empty
* Element has no title attribute or the title attribute is empty
* Element's default semantics were not overridden with role="presentation"
* Element's default semantics were not overridden with role="none"

## Pull requests

- [x] https://github.com/silverstripe/silverstripe-iframe/pull/44
- [x] https://github.com/silverstripe/cwp-starter-theme/pull/136

**Comment by NightJar** [comment]
To clarify for people wondering why this is necessary (the title attribute is technically optional), it is an accessibility issue: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/iframe#Accessibility_concerns

**Comment by robbieaverill** [comment]
@silverstripeux are you happy for me to use "Targeted page" or something like that as the title for this?

**Comment by robbieaverill** [comment]
We currently have a screen reader notice above the iframe saying:

> Please note the following section of content is possibly being delivered from an external source (IFRAME in HTML terms), and may present unusual experiences for screen readers.

I'll set the title to `Target iframe page` for screen readers only for now.

**Comment by sachajudd** [comment]
I think using "Frame content" doesn't provide screen readers with very useful information for what the frame actually contains.
> "The objective of this technique is to demonstrate the use of the title attribute of the frame or iframe element to *describe the contents of each frame.*" [Techniques for WCAG](https://www.w3.org/TR/WCAG20-TECHS/H64.html)
e.g. [website title attribute example](https://thepaciellogroup.github.io/AT-browser-tests/test-files/iframe-title.html)

Can we make this CMS editable? This would then have the same functionality as how an image works at the moment for alternative text. We could have "Frame URL" and "Frame title" with a help description something along the lines of "Description of the iframe contents for screen readers."

**Comment by robbieaverill** [comment]
Sweet, agreed. I’ve updated the PRs.
