### ISSUE TITLE
JQuery > 1.8 compatibility

### ISSUE THREAD

**Issue by mxmclaudel** [silverstripe/silverstripe-iframe#52]
Since JQuery 1.8, `window.load` is deprecated (and removed in later versions), `$(window).on('load', function() {});` should be used instead.

IFrame content never display when using JQuery 3.4.1.

**Comment by emteknetnz** [comment]
Hi, thanks for letting us know :-)

**Comment by emteknetnz** [comment]
I've merged the linked PR
